config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root to: "home#index"
  get '/about', to: 'about#index'
  resources :blogs
  resources :blog_categories
  resources :categories
  resources :skills
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :category

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def blank_stars
    5 - rating.to_i
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :category_id, :progress, :color, :avatar, :rating)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_with(model: skill, local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :skill_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= collection_select(:skill, :category_id, Category.all, :id, :name_with_state) %>
  </div>

  <div class="field">
    <%= form.label :progress %>
    <%= form.text_field :progress, id: :skill_progress %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.select :color, options_for_select(['success', 'primary', 'danger', 'warning', 'info'])%>
  </div>

<div class="field">
  <%= form.label "Avatar(editorial skills only)" %>
  <%= form.file_field :avatar %>
</div>

<div class="field">
  <%= form.label :rating %>
  <%= form.text_field :rating, id: :skill_rating %>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<div class="container">
  <h1>Skills</h1>

  <% @skills.each do |skill| %>
  <%= link_to skill_path(skill), id:"link" do %>
    <%= skill.name %> <%= progress_bar skill.progress.to_f, alternative: skill.color, label: true, id:'progress-bar' %>
    <% end %>
  <% end %>

  <br>

  <%= link_to 'New Skill', new_skill_path %>

</div>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
  <%= image_tag @skill.avatar.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>|
  <%= link_to 'Destroy', @skill, method: :delete, data: { confirm: 'Are you sure?' } %>