config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root to: "home#index"
  get '/about', to: 'about#index'
  resources :blogs
  resources :blog_categories
  resources :categories
  resources :skills
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @web_design = Category.find_by(name: "Web design")
    @videography = Category.find_by(name: "Videography")
    @web_designs = Project.where(category_id: @web_design.id)
    @video_projects = Project.where(category_id: @videography.id)
  end
end

app/views/home/_preloader.html.erb
<!-- The preloader -->
 <div class="preloader">
<div class="msee-b">
<span>
  <span></span>
  <span></span>
  <span></span>
  <span></span>
</span>
<div class="base">
  <span></span>
  <div class="face"></div>
</div>
</div>
<div class="longfazers">
<span></span>
<span></span>
<span></span>
<span></span>
</div>
<h1 class="preloader-heading">Redirecting</h1>
<div class="loader-section section-left"></div>
<div class="loader-section section-right"></div>
</div>

app/views/home/index.html.erb
<div class="container-fluid start">
  <div class="container mwanzo">
    <h1 class="animated bounce" id="name">Lewis Nyoike</h1>
    <h2 class="animated fadeInDownBig"id="slogan">I bulid <span id="awesome">awesome</span> things</h2>
    <h2 class="animated fadeInDown" id="slogan-two">For <span id="awesome">Awesome</span> people</h2>
    <h3 id="scroll"> Scroll <br><br><img class="animated infinite bounce" id="bt" src="https://png.icons8.com/android/38/000000/expand-arrow.png"></h3>
  </div>
</div>
<div class="container-fluid projects">
  <h2 id="projects-header">My projects</h2>
  <hr id="under-ph">
  <div class="container">
    <h3 id="sub-header"><%= @web_design.name %></h3><br>
    <div class="row">
      <% @web_designso = @web_designs.first(6).sort {|a, b| b[:created_at] <=> a[:created_at]} %>
      <% @web_designso.each do |project| %>
      <div class="col-md-4 col-sm-6 col-xs-6 card">
        <div class="image-main">
          <%= link_to project_path(project), id:"link" do %>
          <%= image_tag project.cover_photo.url(:large), class:"img-responsive", id:"image-boki"%>
          <% end %>
        </div>
        <div class="container content">
          <%= link_to project_path(project), id:"link" do %>
          <h4 id="project-title"><%= project.title %></h4>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <br>
    <h3 id="sub-header"><%= @videography.name %></h3><br>
    <div class="row">
      <% @video_projectso = @video_projects.first(3).sort {|a, b| b[:created_at] <=> a[:created_at]} %>
      <% @video_projectso.each do |project| %>
      <div class="col-md-4 col-sm-6 col-xs-6 card">
        <div class="image-main">
          <%= link_to project_path(project), id:"link" do %>
          <%= image_tag project.cover_photo.url(:large), class:"img-responsive", id:"image-boki"%>
          <% end %>
        </div>
        <div class="container content">
          <%= link_to project_path(project), id:"link" do %>
          <h4 id="project-title"><%= project.title %></h4>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container-fluid bottom-home">
  <h1 id="bottom-headline">Who is this guy?</h1>
  <%= link_to about_path, id:"link" do %>
  <button type="button" name="button" class="btn find-out-button">Let's find out</button>
  <% end %>
</div>