config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root to: "home#index"
  get '/about', to: 'about#index'
  resources :blogs
  resources :blog_categories
  resources :categories
  resources :skills
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  has_many :blogs

  def name_with_state
  "#{name}"
  end
end

app/controllers/blog_categories_controller.rb
class BlogCategoriesController < ApplicationController
  before_action :set_blog_category, only: [:show, :edit, :update, :destroy]

  # GET /blog_categories
  # GET /blog_categories.json
  def index
    @blog_categories = BlogCategory.all
  end

  # GET /blog_categories/1
  # GET /blog_categories/1.json
  def show
  end

  # GET /blog_categories/new
  def new
    @blog_category = BlogCategory.new
  end

  # GET /blog_categories/1/edit
  def edit
  end

  # POST /blog_categories
  # POST /blog_categories.json
  def create
    @blog_category = BlogCategory.new(blog_category_params)

    respond_to do |format|
      if @blog_category.save
        format.html { redirect_to @blog_category, notice: 'Blog category was successfully created.' }
        format.json { render :show, status: :created, location: @blog_category }
      else
        format.html { render :new }
        format.json { render json: @blog_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_categories/1
  # PATCH/PUT /blog_categories/1.json
  def update
    respond_to do |format|
      if @blog_category.update(blog_category_params)
        format.html { redirect_to @blog_category, notice: 'Blog category was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_category }
      else
        format.html { render :edit }
        format.json { render json: @blog_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_categories/1
  # DELETE /blog_categories/1.json
  def destroy
    @blog_category.destroy
    respond_to do |format|
      format.html { redirect_to blog_categories_url, notice: 'Blog category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_category
      @blog_category = BlogCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_category_params
      params.require(:blog_category).permit(:name)
    end
end

app/helpers/blog_categories_helper.rb
module BlogCategoriesHelper
end

app/views/blog_categories/_form.html.erb
<%= form_with(model: blog_category, local: true) do |form| %>
  <% if blog_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_category.errors.count, "error") %> prohibited this blog_category from being saved:</h2>

      <ul>
      <% blog_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :blog_category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_categories/edit.html.erb
<h1>Editing Blog Category</h1>

<%= render 'form', blog_category: @blog_category %>

<%= link_to 'Show', @blog_category %> |
<%= link_to 'Back', blog_categories_path %>

app/views/blog_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_categories.each do |blog_category| %>
      <tr>
        <td><%= blog_category.name %></td>
        <td><%= link_to 'Show', blog_category %></td>
        <td><%= link_to 'Edit', edit_blog_category_path(blog_category) %></td>
        <td><%= link_to 'Destroy', blog_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Category', new_blog_category_path %>

app/views/blog_categories/new.html.erb
<h1>New Blog Category</h1>

<%= render 'form', blog_category: @blog_category %>

<%= link_to 'Back', blog_categories_path %>

app/views/blog_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog_category.name %>
</p>

<%= link_to 'Edit', edit_blog_category_path(@blog_category) %> |
<%= link_to 'Back', blog_categories_path %>